services:
  rocketmq-namesrv:
    image: apache/rocketmq:5.3.0
    container_name: rocketmq-namesrv
    command: sh mqnamesrv
    ports:
      - "9876:9876"
    environment:
      JAVA_OPT_EXT: "-Xms256m -Xmx256m"
    networks:
      - rocketmq

  rocketmq-broker:
    image: apache/rocketmq:5.3.0
    container_name: rocketmq-broker
    command: sh mqbroker -n rocketmq-namesrv:9876 -c /opt/rocketmq/conf/broker.conf
    ports:
      - "10911:10911"
      - "10909:10909"
    environment:
      JAVA_OPT_EXT: "-Xms256m -Xmx256m"
      NAMESRV_ADDR: "rocketmq-namesrv:9876"
    depends_on:
      - rocketmq-namesrv
    volumes:
      - ./docker/rocketmq/broker.conf:/opt/rocketmq/conf/broker.conf
    networks:
      - rocketmq

networks:
  rocketmq:
    driver: bridge
