#################################################
## mysql servance config
canal.instance.mysql.slaveId=0

# position info
canal.instance.master.address=host.docker.internal:3306
canal.instance.master.gtid=

# username/password
canal.instance.dbUsername=canal
canal.instance.dbPassword=canal123456
canal.instance.connectionCharset=UTF-8
canal.instance.defaultDatabaseName=cloud_tea_db

# table regex
canal.instance.filter.regex=cloud_tea_db\\..*

# mq config
canal.mq.topic=canal-topic
#################################################
