# ======================== 集群配置 ========================
brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 1
brokerRole = SLAVE
flushDiskType = ASYNC_FLUSH

# ======================== 存储配置 ========================
deleteWhen = 04
fileReservedTime = 72
storePathRootDir = /home/rocketmq/store
storePathCommitLog = /home/rocketmq/store/commitlog

# ======================== 网络配置 ========================
namesrvAddr = rocketmq-namesrv:9876
brokerIP1 = host.docker.internal

# ======================== 安全配置 ========================
autoCreateTopicEnable = false

# ======================== 消息配置 ========================
maxMessageSize = 4194304

